### PR TITLE
Added more scenarios

### PR DESCRIPTION
**Pull request by Shikib**
plane_search
plane_reserve
restaurant_reserve
restaurant_search
party_plan
party_rsvp

Schemas, user instruction templates/dbs, modified APIs. Tested that all APIs are functional.

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @amn41 will take a look at it as soon as possible ✨

**Review by JEM-Mosig — APPROVED** [review]
Before merging: Can you please integrate my changes from the johannes-suggestions PR? It should show the conflicts at the bottom or this PR here.

**Comment by JEM-Mosig** [comment]
@Shikib Actually, can you please first approve https://github.com/RasaHQ/ParlAI/pull/12 ? This fixes the `make_scenarios.py` script, which you then would have to run again.

**Comment by Shikib** [comment]
@JEM-Mosig I'll merge this after you've merged #12

**Comment by JEM-Mosig** [comment]
I just merged #12

**Pull request merged**
